# Generated by Django 5.2.8 on 2025-11-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicdata', '0003_paydtype_alter_vehicletype_options'),
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='model',
        ),
        migrations.AddField(
            model_name='discount',
            name='model',
            field=models.ManyToManyField(to='basicdata.vehiclemodel'),
        ),
    ]
