# Generated by Django 5.2.8 on 2025-11-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0002_remove_discount_brand_remove_discount_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='description',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
