# Generated by Django 5.2.8 on 2025-11-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0004_alter_discount_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='discount_euro_intern',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='discount_percent_intern',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='discount_type',
            field=models.CharField(choices=[('euro', 'Euro-Rabatt'), ('percent', 'Prozent-Rabatt')], default='euro', max_length=10),
        ),
    ]
