# Generated by Django 5.2.8 on 2025-11-25 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0006_alter_discount_discount_percent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='is_active',
        ),
    ]
