# Generated by Django 5.2.8 on 2025-11-25 09:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicdata', '0003_paydtype_alter_vehicletype_options'),
        ('discounts', '0007_remove_discount_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_euro',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Hier wird die Marge für den Verkäufer eingetragen', max_digits=10, null=True, verbose_name='Nachlass in Euro'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_euro_intern',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Hier wird unsere Marge eingetragen', max_digits=10, null=True, verbose_name='Nachlass in Euro intern'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_name',
            field=models.CharField(max_length=100, verbose_name='Nachlassbezeichnung'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_percent',
            field=models.FloatField(blank=True, help_text='Prozentualer Rabatt für den Kunden', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Nachlass in Prozent'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_percent_intern',
            field=models.FloatField(blank=True, help_text='Interne Prozentmarge', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Nachlass in Prozent intern'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_type',
            field=models.CharField(choices=[('euro', 'Euro-Rabatt'), ('percent', 'Prozent-Rabatt')], default='euro', max_length=10, verbose_name='Nachlasstyp'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='model',
            field=models.ManyToManyField(help_text='...', to='basicdata.vehiclemodel', verbose_name='Gültige Fahrzeugmodelle'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='valid_from',
            field=models.DateField(help_text='Ab diesem Datum wird der Nachlass im Siebrecht Copilot sichtbar', verbose_name='Gültig ab'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='valid_to',
            field=models.DateField(blank=True, help_text='Nach Ablauf dieses Datums ist der Nachlass im Copilot nicht mehr sichtbar', null=True, verbose_name='Gültig bis'),
        ),
    ]
