# Generated by Django 5.2.8 on 2025-11-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0008_alter_discount_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='description',
            field=models.CharField(blank=True, help_text='(optional)', max_length=100, null=True, verbose_name='Beschreibung'),
        ),
    ]
