# Generated by Django 5.2.8 on 2025-11-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicdata', '0003_paydtype_alter_vehicletype_options'),
        ('discounts', '0009_alter_discount_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='customer_group',
            field=models.ManyToManyField(help_text='...', to='basicdata.customergroup', verbose_name='Gültige Kundengruppen'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_type',
            field=models.CharField(choices=[('euro', 'Euro'), ('percent', 'Prozent')], default='euro', max_length=10, verbose_name='Nachlasstyp'),
        ),
    ]
