# Generated by Django 5.2.8 on 2025-11-26 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0010_discount_customer_group_alter_discount_discount_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'Nachlass', 'verbose_name_plural': 'Nachlässe'},
        ),
    ]
