# Generated by Django 5.2.8 on 2025-11-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basicdata', '0003_paydtype_alter_vehicletype_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItemTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brands', models.ManyToManyField(blank=True, to='basicdata.brand')),
                ('customer_groups', models.ManyToManyField(blank=True, to='basicdata.customergroup')),
                ('payd_types', models.ManyToManyField(blank=True, to='basicdata.paydtype')),
                ('vehicle_types', models.ManyToManyField(blank=True, to='basicdata.vehicletype')),
            ],
            options={
                'verbose_name': 'Checklistenpunkt Vorlage',
                'verbose_name_plural': 'Checklistenpunkte Vorlagen',
            },
        ),
    ]
