# Generated by Django 5.2.8 on 2025-11-25 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklistitemtemplate',
            options={'verbose_name': 'Checklisteninhalt', 'verbose_name_plural': 'Checklisteninhalte'},
        ),
    ]
