# Generated by Django 5.2.8 on 2026-01-19 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basicdata', '0005_promotioncode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offerNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True)),
                ('upe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('custom_public_values', models.JSONField(default=dict)),
                ('checklist_state', models.JSONField(blank=True, default=dict)),
                ('additional_costs', models.JSONField(default=dict)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basicdata.brand')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('customer_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basicdata.customergroup')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basicdata.vehiclemodel')),
                ('payd_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basicdata.paydtype')),
                ('promotion_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basicdata.promotioncode')),
                ('seller_channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basicdata.sellerchannel')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basicdata.vehicletype')),
            ],
            options={
                'verbose_name': 'Vorgang',
                'verbose_name_plural': 'Vorgänge',
            },
        ),
    ]
