# Generated by Django 5.2.8 on 2026-01-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='additional_costs',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
