# Generated by Django 5.2.8 on 2026-01-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='checklist_state',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
