# Generated by Django 5.2.8 on 2026-01-09 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_checklist_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Vorgang', 'verbose_name_plural': 'Vorgänge'},
        ),
    ]
