# Generated by Django 5.2.8 on 2026-01-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='upe',
            field=models.FloatField(),
        ),
    ]
