# Generated by Django 5.2.8 on 2026-01-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_car_upe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='upe',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
