# Generated by Django 5.2.8 on 2025-11-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicdata', '0002_customergroup_vehicletype_alter_brand_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaydType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bezahlungsart',
                'verbose_name_plural': 'Bezahlungsarten',
            },
        ),
        migrations.AlterModelOptions(
            name='vehicletype',
            options={'verbose_name': 'Fahrzeugtyp', 'verbose_name_plural': 'Fahrzeugtypen'},
        ),
    ]
