# Generated by Django 5.2.8 on 2025-11-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicdata', '0003_paydtype_alter_vehicletype_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Verkaufskanal',
                'verbose_name_plural': 'Verkaufskanäle',
            },
        ),
    ]
