# Generated by Django 5.2.8 on 2026-02-02 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicdata', '0005_promotioncode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemodel',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_models', to='basicdata.brand'),
        ),
    ]
